services:
  client:
    image: node:latest
    working_dir: /client
    volumes: 
      - ../../certificates:/https:ro
      - ../../chat-client:/client
    env_file: 
      - client.env
    command: ["npm","start"]
    networks:
      webapp:
        ipv4_address: 172.20.0.3

  server:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    working_dir: /server
    env_file:
      - server.env
    volumes:
      - ../../certificates:/https:ro
      - ../../chat-server:/server
    command: ["dotnet","watch","run"]
    networks:
      webapp:
        ipv4_address: 172.20.0.2

networks:
  webapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1