services:
  client:
    image: node:latest
    working_dir: /client
    volumes: 
      - ../../certificates:/https:ro
      - ../../chat-client:/client
    command: ["npm","start"]
    environment: 
      - SSL_CRT_FILE=/https/chat.crt
      - SSL_KEY_FILE=/https/chat.key
    networks:
      webapp:
        ipv4_address: 172.20.0.3

  server:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    working_dir: /server
    volumes:
      - ../../certificates:/https:ro
      - ../../chat-server:/server
    command: ["dotnet","watch","run"]
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/chat.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/chat.key
    networks:
      webapp:
        ipv4_address: 172.20.0.2

networks:
  webapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1